### ISSUE TITLE
Uncaught RangeError: Invalid array buffer length

### ISSUE THREAD

**Issue by 5chdn** [5chdn/webgl-accessibility-maps-poc5#33]
On zoom level 9:

```
accessibility.js:598 Uncaught RangeError: Invalid array buffer length
    at new Uint32Array (native)
    at drawGL (http://5chdn.github.io/webgl-accessibility-maps-poc5/accessibility.js:598:24)
    at http://5chdn.github.io/webgl-accessibility-maps-poc5/accessibility.js:410:7
    at Object.getGraph (http://5chdn.github.io/webgl-accessibility-maps-poc5/lib/r360/r360-src.js:2717:13)
    at requestTile (http://5chdn.github.io/webgl-accessibility-maps-poc5/accessibility.js:451:21)
    at getGltfTiles (http://5chdn.github.io/webgl-accessibility-maps-poc5/accessibility.js:381:3)
    at NewClass.gltfTiles.drawTile (http://5chdn.github.io/webgl-accessibility-maps-poc5/accessibility.js:145:5)
    at NewClass._redrawTile (http://5chdn.github.io/webgl-accessibility-maps-poc5/lib/leaflet/leaflet-src.js:3108:8)
    at NewClass._loadTile (http://5chdn.github.io/webgl-accessibility-maps-poc5/lib/leaflet/leaflet-src.js:3122:8)
    at NewClass._addTile (http://5chdn.github.io/webgl-accessibility-maps-poc5/lib/leaflet/leaflet-src.js:2826:8)
```

That's the code in question:

```
    if (tileBuffers[i].getIndexBuffer().length > 65535) {
      // [...]
      let buffer = new Uint32Array(tileBuffers[i].getIndexBuffer());
    }
```

Length is not 0 and not negative, and most likely impossible to be larger than unsigned 32 bit.

**Comment by 5chdn** [comment]
hard to catch this beast.
